# Generated by Django 5.0 on 2023-12-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Fname',
            field=models.CharField(max_length=100),
        ),
    ]
