# Generated by Django 5.0 on 2023-12-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('quali', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=100)),
            ],
        ),
    ]
