# Generated by Django 5.0 on 2023-12-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='dob',
            new_name='Dob',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='Fname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lang',
            new_name='Lang',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lname',
            new_name='Lname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='quali',
            new_name='Quali',
        ),
    ]
