# Generated by Django 5.0 on 2023-12-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_age_student_age_rename_dob_student_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Dob',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Lang',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Quali',
            new_name='Qualification',
        ),
        migrations.AlterField(
            model_name='student',
            name='Fname',
            field=models.CharField(max_length=100, verbose_name='FNAME'),
        ),
    ]
